no-hooks = true
pkgname = "models"
output = "internal/models"

# Adds global variant of the generated functions, more on this later.
add-global-variants = false

# Wipes the models directory before generation, useful for regenerating.
wipe = true

# Generates code for enum types as well.
add-enum-types = true

[psql]
# Connection params are injected via env vars (PSQL_*)
# As those are supplied via the env, you cannot overwrite the here!
# see https://github.com/volatiletech/sqlboiler/issues/678
# see https://github.com/volatiletech/sqlboiler/pull/615
blacklist = ["migrations"]
